### PR TITLE
Add getGop method and its unit test.

### PR DESCRIPTION
**Pull request by StylishPanther**
# Background

Add multiplier method on calculator class

# Test Result

[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from TestCaseName
[ RUN      ] TestCaseName.TestName
[       OK ] TestCaseName.TestName (0 ms)
[ RUN      ] TestCaseName.test_getGop
[       OK ] TestCaseName.test_getGop (0 ms)
[----------] 2 tests from TestCaseName (1 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (1 ms total)
[  PASSED  ] 2 tests.

### CODE REVIEW

**Review by Kanaish — APPROVED** [review]
tc까지 같이 확인 했습니다.

**Review by wonmyth — APPROVED** [review]
review done.
구현 감사합니다.

**Review by bsjn16sw — APPROVED** [review]
코드와 테스트 결과 확인하였습니다!

**Review by jiyeon-08 — APPROVED** [review]
확인했습니다~!

**Review by miryo9yd — APPROVED** [review]
리뷰했습니다.

**Pull request merged**
